### ISSUE TITLE
CSV to JSON

### ISSUE THREAD

**Issue by igorfelipee** [GDGDuqueDeCaxias/gdg-event-sort#2]
We need to create a function to read a csv archive and convert it to JSON.

**Comment by gabrielclima** [comment]
https://github.com/martindrapeau/csvjson-app we can use this

**Comment by igorfelipee** [comment]
ta mandado

**Comment by gabrielclima** [comment]
https://gist.github.com/jonmaim/7b896cf5c8cfe932a3dd

**Comment by gabrielclima** [comment]
Um outro gist funcionando.
https://gist.github.com/iwek/7154578

**Comment by gabrielclima** [comment]
Adicionei outra função de conversão ;)
